# Generated by Django 4.2.2 on 2023-06-17 16:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='Заголовок поста')),
                ('description', models.TextField(verbose_name='Описание поста')),
                ('text', models.TextField(verbose_name='Текст новости')),
                ('post_type', models.IntegerField(choices=[(1, 'Исследование'), (2, 'Обсуждение'), (3, 'Вопрос')], default=2, verbose_name='Тип поста')),
                ('date_post', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания поста')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь создавший пост')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('date_comment', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания комментария')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь оставивший комментарий')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
