# Generated by Django 4.2.2 on 2023-06-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_ip_post_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
