# Generated by Django 4.2.2 on 2023-06-29 17:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_alter_country_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='user',
        ),
        migrations.AlterField(
            model_name='country',
            name='id',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='user_c', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
